# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

# MkDocs configuration
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# Python environment setup
python:
  pre_install:
    - curl -sSf https://astral.sh/uv/install.sh | sh

  install:
    - method: uv
      path: .
      extra_requirements: ["dev"]
      use_system_python: true

# Build PDF and ePub output
formats:
  - pdf
  - epub

# Path to the documentation source
doc_path: docs
