# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.8

pipelines:
  default:
    - step:
        name: Deploy to test
        deployment: test
        max-time: 5
        caches:
          - pip
        script:
          - make clean requirements test
  branches:
    master:
      - step:
          name: Deploy to production
          deployment: production
          max-time: 5
          caches:
            - pip
          script:
            - python -m pip freeze
            - make clean requirements test sdist
            - find dist -name '*.gz' -exec curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"{}" \;
