#!python

"""
PYTHONPATH=$(pwd) scripts/audiolibrarian /media/BlackBox/Music/flac/some_file

"""
import argparse
import re
import subprocess
import sys

from audiolibrarian.audiolibrarian import AudioLibrarian, GenreManager

REQUIRED_EXE = ("cd-paranoia", "eject", "fdkaac", "flac", "lame", "sndfile-convert", "wavegain")


def check_deps():
    missing = []
    for exe in REQUIRED_EXE:
        r = subprocess.run(("which", exe), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        if r.returncode:
            missing.append(exe)
    if missing:
        print(f"\nMissing required executable(s): {', '.join(missing)}\n")
        sys.exit(1)


def parse_args():
    parser = argparse.ArgumentParser(description="Audio Librarian")
    subparsers = parser.add_subparsers(title="command", dest="command")

    # global options
    parser.add_argument("--db", default="mb", choices=("discogs", "mb"), help="database")
    parser.add_argument("--verbose", "-v", action="store_true", help="verbose output")

    # convert from files
    _convert = subparsers.add_parser("convert", help="convert music from files")
    _convert.add_argument("--artist", "-a", help="provide artist (ignore tags)")
    _convert.add_argument("--album", "-m", help="provide album (ignore tags)")
    _convert.add_argument("--disc", "-d", help="format: x/y: disc x of y for multi-disc release")
    _convert.add_argument("filename", nargs="+", help="directory name or audio file name")

    # rip from CD
    _rip = subparsers.add_parser("rip", help="rip music from a CD")
    _rip.add_argument("--artist", "-a", help="provide artist")
    _rip.add_argument("--album", "-m", help="provide album")
    _rip.add_argument("--disc", "-d", default="1/1", help="x/y: disc x of y; multi-disc release")

    # genre management
    _genre = subparsers.add_parser("genre", help="manager MB genre")
    _genre.add_argument("directory", nargs="+", help="root of directory tree to process")
    _genre_action = _genre.add_mutually_exclusive_group()
    _genre_action.add_argument("--tag", action="store_true", help="update tags")
    _genre_action.add_argument("--update", action="store_true", help="update Musicbrainz")

    return _validate_args(parser.parse_args())


def _validate_args(a):
    print(a)
    if "disc" in a and a.disc:
        if not re.match(r"\d+/\d+", a.disc):
            print("Invalid --disc specification; should be x/y")
            sys.exit(-1)
    return a


if __name__ == "__main__":
    args = parse_args()
    if args.verbose:
        print(args)
    check_deps()
    if args.command == "genre":
        GenreManager(args)
    else:
        AudioLibrarian(args)
