#!python

"""
PYTHONPATH=$(pwd) scripts/audiolibrarian /media/BlackBox/Music/flac/some_file

"""
import argparse
import re
import subprocess
import sys

from audiolibrarian.audiolibrarian import AudioLibrarian

REQUIRED_EXE = ("fdkaac", "flac", "lame", "sndfile-convert", "wavegain")


def check_deps():
    missing = []
    for exe in REQUIRED_EXE:
        r = subprocess.run(("which", exe), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        if r.returncode:
            missing.append(exe)
    if missing:
        print(f"\nMissing required executable(s): {', '.join(missing)}\n")
        sys.exit(1)


def parse_args():
    parser = argparse.ArgumentParser(description="Audio Librarian")
    parser.add_argument("--artist", "-a", help="provide artist")
    parser.add_argument("--album", "-m", help="provide album")
    parser.add_argument("--db", default="mb", choices=("discogs", "mb"), help="database")
    parser.add_argument("--disc", "-d", help="format: x/y: disc x of y for multi-disc release")
    parser.add_argument("--verbose", "-v", action="store_true", help="verbose output")
    parser.add_argument("files", nargs="+", help="audio files")

    return validate_args(parser.parse_args())


def validate_args(args):
    if args.disc:
        if not re.match(r"\d+/\d+", args.disc):
            print("Invalid --disc specification; should be x/y")
            sys.exit(-1)
    return args


if __name__ == "__main__":
    check_deps()
    AudioLibrarian(parse_args())
